### ISSUE TITLE
No Updates to Drug Enforcement Recall API

### ISSUE THREAD

**Issue by al2882** [FDA/openfda#182] opened 2022-01-12 17:17 UTC
I have been trying to test the functionality of the Drug Enforcement Report API since last week. 

There were 2 drugs that were class 1 recalls: on 2022-01-05. 
It is now 2022-01-12 and there have been no updates:
`https://api.fda.gov/drug/enforcement.json?search=product_type:%22Drugs%22+AND+classification:%22Class+I%22+AND+report_date:20220105&limit=10`

What is the actual schedule for API updates?

**Comment by dkrylovsb** [comment] 2022-01-12 17:44
We update the Enforcement endpoints weekly; however, the most recent update has gotten a bit behind the schedule due to a minor technical issue. We are in process of catching up as we speak and will report back here once that activity is completed. Sorry about the inconvenience.

**Comment by dkrylovsb** [comment] 2022-01-13 12:44
The endpoint has been refreshed and the issue is now fixed.

**Closed by dkrylovsb** 2022-01-13 12:44 UTC
