### ISSUE TITLE
"Recall_number" not returned in Device Enforcement API

### ISSUE THREAD

**Issue by SG842** [FDA/openfda#41] opened 2014-11-07 01:11 UTC
The field "recall_number" is not returned in the following though the Field Reference for the Enforcement Report data mentions it:

https://api.fda.gov/device/enforcement.json?&limit=2

Can someone please tell me why it is not being returned and how to get the recall number to be returned in the API

**Comment by rjpower** [comment] 2015-02-04 23:40
Duplicate of issue #34.

(The recall_number is available in our data source, but not currently not being indexed.  We will update issue #34 when progress is made on this).

**Closed** 2015-02-04 23:40 UTC
Labels: duplicate
